#############################################################################
# Makefile for building: Spellbook
# Generated by qmake (3.1) (Qt 5.11.2)
# Project:  Spellbook.pro
# Template: app
# Command: /home/jon/src/mxe/usr/i686-w64-mingw32.static/qt5/bin/qmake -o Makefile Spellbook.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = /home/jon/src/mxe/usr/i686-w64-mingw32.static/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/jon/src/mxe/usr/i686-w64-mingw32.static/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/jon/src/mxe/usr/i686-w64-mingw32.static/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: Spellbook.pro ../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/win32-g++/qmake.conf ../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/spec_pre.prf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/qdevice.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/device_config.prf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/sanitize.conf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/gcc-base.conf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/g++-base.conf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/angle.conf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/windows-vulkan.conf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/g++-win32.conf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/qconfig.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3drender.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axbase.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axbase_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axcontainer.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axserver.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axserver_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_charts.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_core.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_datavisualization.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gui.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_help.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_help_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_location.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_location_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_network.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_nfc.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_positioning.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_purchasing.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qml.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_script.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_script_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_scxml.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sensors.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_serialport.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sql.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_svg.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_uitools.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_websockets.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_webview.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_webview_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_winextras.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_winextras_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xml.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_defaultgeometryloader.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_dsengine.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_gltfgeometryloader.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_gltfsceneexport.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_gltfsceneimport.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qflatpak.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qgif.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qicns.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qico.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qjp2.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qminimal.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmng.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlmysql.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlodbc.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlpsql.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqltds.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsvg.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtaudio_windows.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtexttospeech_sapi.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtga.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtiff.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtpassthrucanbus.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtpeakcanbus.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtposition_geoclue.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtsysteccanbus.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qttinycanbus.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtvectorcanbus.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwbmp.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwebp.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwindows.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwindowsvistastyle.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_scene2d.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_xinputgamepad.pri \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt_functions.prf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt_config.prf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/win32-g++/qmake.conf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/exclusive_builds.prf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/toolchain.prf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/default_pre.prf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/win32/default_pre.prf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/resolve_config.prf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/exclusive_builds_post.prf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/default_post.prf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/precompile_header.prf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/warn_on.prf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt.prf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/resources.prf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/moc.prf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/win32/opengl.prf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/uic.prf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qmake_use.prf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/file_copies.prf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/win32/windows.prf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/testcase_targets.prf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/exceptions.prf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/yacc.prf \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/lex.prf \
		Spellbook.pro \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/lib/qtmain.prl \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/plugins/styles/qwindowsvistastyle.prl \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/plugins/platforms/qwindows.prl \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qgif.prl \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qicns.prl \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qico.prl \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qjp2.prl \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qjpeg.prl \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qmng.prl \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qtga.prl \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qtiff.prl \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qwbmp.prl \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qwebp.prl \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/lib/Qt5Widgets.prl \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/lib/Qt5Gui.prl \
		../../src/mxe/usr/i686-w64-mingw32.static/qt5/lib/Qt5Core.prl
	$(QMAKE) -o Makefile Spellbook.pro
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/spec_pre.prf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/qdevice.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/device_config.prf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/sanitize.conf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/gcc-base.conf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/g++-base.conf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/angle.conf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/windows-vulkan.conf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/g++-win32.conf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/qconfig.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3danimation.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3danimation_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dcore.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dextras.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dinput.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquick.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3drender.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axbase.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axbase_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axcontainer.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axcontainer_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axserver.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axserver_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_charts.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_charts_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_concurrent.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_core.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_core_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_datavisualization.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_dbus.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gamepad.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gamepad_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gui.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gui_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_help.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_help_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_location.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_location_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimedia.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_network.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_network_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_networkauth.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_networkauth_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_nfc.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_opengl.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_positioning.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_positioningquick.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_printsupport.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_purchasing.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_purchasing_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qml.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qml_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmltest.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_script.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_script_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_scripttools.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_scxml.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_scxml_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sensors.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_serialbus.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_serialbus_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_serialport.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sql.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sql_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_svg.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_svg_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_testlib.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_texttospeech.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_uitools.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_webchannel.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_websockets.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_webview.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_webview_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_widgets.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_winextras.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_winextras_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xml.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xml_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_zlib_private.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_defaultgeometryloader.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_dsengine.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_gltfgeometryloader.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_gltfsceneexport.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_gltfsceneimport.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qflatpak.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qgif.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qicns.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qico.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qjp2.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qjpeg.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qminimal.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_local.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_messages.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_native.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_server.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmng.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qoffscreen.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlite.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlmysql.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlodbc.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlpsql.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqltds.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsvg.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsvgicon.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtaudio_windows.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtexttospeech_sapi.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtga.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtiff.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtpassthrucanbus.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtpeakcanbus.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtposition_geoclue.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtsysteccanbus.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qttinycanbus.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtvectorcanbus.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwbmp.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwebp.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwindows.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwindowsvistastyle.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_scene2d.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_windowsprintersupport.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_xinputgamepad.pri:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt_functions.prf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt_config.prf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/win32-g++/qmake.conf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/exclusive_builds.prf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/toolchain.prf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/default_pre.prf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/win32/default_pre.prf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/resolve_config.prf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/exclusive_builds_post.prf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/default_post.prf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/precompile_header.prf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/warn_on.prf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt.prf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/resources.prf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/moc.prf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/win32/opengl.prf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/uic.prf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qmake_use.prf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/file_copies.prf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/win32/windows.prf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/testcase_targets.prf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/exceptions.prf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/yacc.prf:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/lex.prf:
Spellbook.pro:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/lib/qtmain.prl:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/plugins/styles/qwindowsvistastyle.prl:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/plugins/platforms/qwindows.prl:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qgif.prl:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qicns.prl:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qico.prl:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qjp2.prl:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qjpeg.prl:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qmng.prl:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qtga.prl:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qtiff.prl:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qwbmp.prl:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qwebp.prl:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/lib/Qt5Widgets.prl:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/lib/Qt5Gui.prl:
../../src/mxe/usr/i686-w64-mingw32.static/qt5/lib/Qt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Spellbook.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) /home/jon/git/Spellbook/spellbook_plugin_import.cpp .qmake.stash

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
